apiVersion: v1
type: postrenderer/v1
name: vault-crd-helm-renderer
version: v1.0.8
runtime: subprocess
runtimeConfig:
  platformCommand:
  - command: java
    args:
    - -jar
    - ${HELM_PLUGIN_DIR}/vault-crd-helm-renderer.jar
  platformHooks:
    install:
#    - command: curl
#      args:
#      - -L
#      - -o
#      - /tmp/vault-crd-helm-renderer.jar
#      - https://github.com/DaspawnW/vault-crd-helm-renderer/releases/download/v1.0.8/vault-crd-helm-renderer.jar
    - command: echo
      args:
      - "${HELM_PLUGIN_DIR}"
    update:
    - command: curl
      args:
      - -L
      - -o
      - /tmp/vault-crd-helm-renderer.jar
      - https://github.com/DaspawnW/vault-crd-helm-renderer/releases/download/v1.0.8/vault-crd-helm-renderer.jar